### ISSUE TITLE
Fails to load with Next.js (but there is a workaround)

### ISSUE THREAD

**Issue by daveagill** [odedglas/react-linear-gradient-picker#19]
## The issue
This component fails to load when used in Next.js.

This library (or I think a dependency) is making use of DOMParser during the initial page-load which fails because Next.js does static pre-rendering/SSR for everything and DOMParser is a browser API and therefore not available during pre-rendering.

## The stack trace
```
ReferenceError: DOMParser is not defined

Module.e.m.t
file:///Users/david/Documents/slantt-saas/slantt/node_modules/react-linear-gradient-picker/dist/index.js (1:8991)
e
file:///Users/david/Documents/slantt-saas/slantt/node_modules/react-linear-gradient-picker/dist/index.js (1:12235)
<unknown>
file:///Users/david/Documents/slantt-saas/slantt/node_modules/react-linear-gradient-picker/dist/index.js (1:12139)
Object.<anonymous>
file:///Users/david/Documents/slantt-saas/slantt/node_modules/react-linear-gradient-picker/dist/index.js (1:12290)
n
file:///Users/david/Documents/slantt-saas/slantt/node_modules/react-linear-gradient-picker/dist/index.js (1:403)
Module.<anonymous>
file:///Users/david/Documents/slantt-saas/slantt/node_modules/react-linear-gradient-picker/dist/index.js (1:20132)
n
file:///Users/david/Documents/slantt-saas/slantt/node_modules/react-linear-gradient-picker/dist/index.js (1:403)
<unknown>
file:///Users/david/Documents/slantt-saas/slantt/node_modules/react-linear-gradient-picker/dist/index.js (1:1202)
<unknown>
file:///Users/david/Documents/slantt-saas/slantt/node_modules/react-linear-gradient-picker/dist/index.js (1:1212)
<unknown>
file:///Users/david/Documents/slantt-saas/slantt/node_modules/react-linear-gradient-picker/dist/index.js (1:81)
```

## The workaround
The solution is to import the module dynamically:

```
import dynamic from 'next/dynamic'
const GradientPicker = dynamic(() => import('react-linear-gradient-picker').then(m => m.GradientPicker), { ssr: false });

// use GradientPicker like normal
```

## A better fix?
I am thinking it is probably somehow possible to avoid invoking DOMParser during page-load which would avoid the issue of it not being available during pre-rendering.  Making this component easier to integrate with Next.js is a worthwhile thing IMO :)

**Comment by odeadglaz** [comment]
Sure it can be done altho even If I delay the DOMParses usage to page load, It would mean upon SSR, the `<GradientPicker/>` component preview wont be able to parse it's preview display.

I can think of a couple of approaches we can take here:
1. Display some skeleton background preview upon SSR, and switch with true preview over the client.
2. Make dom parser lib isomorphic using `dom-parser` on server, and native browser DOMParser, altho I'm afraid of mismatch between to two API results.

WDYT?

**Comment by daveagill** [comment]
I just had a quick look and I am not sure that DOMParser is used by this lib, is it?

Here's my observations / thoughts:

1) I believe the preview and therefore the parser is only used by `GradientPickerPopover`  - Ideally anyone not using that component shouldn't be impacted (but they will be because DOMParser is instantiated [during module load](https://github.com/odedglas/linear-gradient-parser/blob/master/src/utils/parseLinearGradient/index.js#L4)).

2) The [preview code](https://github.com/odedglas/react-linear-gradient-picker/blob/ac735e93e18d4de4548c2575625f49b2509b0aca/src/lib/getGradientPreview/index.js#L16) uses the result of `getGradientCords` which is an `object` type and I believe [here](https://github.com/odedglas/linear-gradient-parser/blob/master/src/index.js#L41) it will therefore avoid calling `parseLinearGradient` (which uses DOMParser) - So DOMParser is never actually utilized via this lib I believe(?)

If I'm right about that, then easiest fix may be just to instantiate a new DOMParser as-needed by `parseLinearGradient` instead of globally at the module level.

**Comment by odeadglaz** [comment]
Yea make total sense, ill adjust it 👍

**Comment by odeadglaz** [comment]
I just released a new version using the parser fix -> `1.2.2`

**Comment by daveagill** [comment]
Just given it a spin in my project but unfortunately still get the same error - in fact it looks like _exactly_ the same error with the same line numbers. I'm def seeing 1.2.2 in my node_modules and the code change looks solid to me.

Any chance you forgot to `npm update` or forgot to rebuild `dist/index.js` before pushing to npm?

**Comment by odeadglaz** [comment]
Yea I might miss that, I ensured it was present on 1.2.3, sorry for the hassle 👍

**Comment by daveagill** [comment]
No worries at all 👍

We're getting closer but this seems to be a little more complicated than it first seemed:  There are are now new loading issues in Next.js:.
```
ReferenceError: document is not defined

file:///...../node_modules/react-linear-gradient-picker/dist/index.js (1:2580)
```

Looking at position 2580 in index.js I believe the culprit is the style-loader plugin used by webpack. Apparently it's a [common issue](https://stackoverflow.com/a/62342517) that style-loader is not next.js friendly but there are alternatives: https://github.com/webpack-contrib/mini-css-extract-plugin

This is an interesting one!

**Comment by odeadglaz** [comment]
Yea it's being used while parsing as-well, Ill consider different strategy for that one 👍

**Comment by jamesalester** [comment]
I'm also getting the `document is not defined` issue, is there a workaround?

**Comment by daveagill** [comment]
> I'm also getting the `document is not defined` issue, is there a workaround?

Hi James,

Yes there is. You can tell next.js to import dynamically and without server-side-rendering:
```
import dynamic from 'next/dynamic'
const GradientPicker = dynamic(() => import('react-linear-gradient-picker').then(m => m.GradientPicker), { ssr: false });


// now use <GradientPicker> like normal
```

**Comment by odeadglaz** [comment]
Yea as said above, for now, you can just avoid SSR phase, which would work as normal. I hope I would release a fix for it over this weekend, so you could remove this workaround from your end.

**Comment by jamesalester** [comment]
Awesome thanks @daveagill , i'll give that a try later. That would be great @odeadglaz , I'm not really making use of ssr in my project so there's no huge rush for me if the workaround works but it's great to see that this package is well maintained 👏

**Comment by odeadglaz** [comment]
Hey, I pushed a fix for this one, tho released it under `2.0.0` not to break any existing consumers since now it requires the consumer to manually import the css file ( if wished ) from the package dist e.g ->
```import 'react-linear-gradient-picker/dist/index.css';```

**Comment by daveagill** [comment]
Make sense!
I'll give this a try in [my project](https://slantt.co/) later and report back.

**Comment by daveagill** [comment]
Looks like you've cracked it and works great on v2.0.0.

Thanks for the time and effort put in to address this.

I shall close this issue 👍
